### ISSUE TITLE
File of "dev.small.pickle" and "test.data.cfo.pickle"

### ISSUE THREAD

**Issue by chaojieji** [wudapeng268/KBQA-Baseline#1]
Hi,
      Thanks for your contribution in KB-QA. I have downloaded your source code and attempted to execute it. Task of focus prune works very well. But the mission of kbqa doesn't run. May I need the file "dev.small.pickle" and "test.data.cfo.pickle", but I found nothing about it in the resources. Is it possible for your help? Thanks.

**Comment by wudapeng268** [comment]
update file, you can find link in README.md

**Comment by chaojieji** [comment]
Thanks for your support immediately ! I'll check it.

**Comment by chaojieji** [comment]
It's all OK.  Thanks.

**Comment by deepcode-debug** [comment]
Hi, thanks for the great project. Unfortunately, we are not able to download from baidu cloud. is it possible to share it from dropbox or some other cloud providers?

**Comment by rashad101** [comment]
> Hi, thanks for the great project. Unfortunately, we are not able to download from baidu cloud. is it possible to share it from dropbox or some other cloud providers?

Same here. Cannot download from the baidu cloud. @wudapeng268  is it possible to upload these two files in an easily accessible cloud providers such as google drive or dropbox?

**Comment by wudapeng268** [comment]
thanks for your interest, the google drive link is at 
https://drive.google.com/drive/folders/1cmO7QdcUgNeB8hpsE5Bj6AdtIFKbHyCW?usp=sharing
