### ISSUE TITLE
Can't download dev and test from baidu cloud

### ISSUE THREAD

**Issue by deepcode-debug** [wudapeng268/KBQA-Baseline#2]
Hi, thanks for the great project. Unfortunately, we are not able to download from Baidu cloud. is it possible to share it from dropbox or some other cloud providers?

_Originally posted by @DeepInEvil in https://github.com/wudapeng268/KBQA-Baseline/issues/1#issuecomment-735942107_

**Comment by wudapeng268** [comment]
Thanks for your interest, updated readme.
